---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: install python 2 on Ubuntu
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: all-nodes
  roles:
    - kubernetes-common

- hosts: kube-master
  roles:
    - kubernetes-master

- hosts: kube-nodes
  roles:
    - kubernetes-nodes
